#+title: Building my Ultimate Emacs Configuration
#+author: nucholab

#+begin_quote
I use emacs, which might be thought of as a thermonuclear word processor [...] emacs outshines all other editing software in approximately the same way that the noonday sun does the stars. It is not just bigger and brighter; it simply makes everything else vanish. ---Neal Stephenson
#+end_quote

This repo is to build my Emacs configuration. The plan is to start with the simplest vanilla config and gradually add [[file:progression_plan.org][features]]. Note that this configuration will, at least at first, assume Emacs version >= 29. For example, assuming that =modus themes=, =eglot=, and =use-packages= are built-in.

** How to use
Currently I'm using the "legacy" config contained in my dotfiles by defailt. Starting with Emacs 29, it is easy to run different configs so I start the one in this repo with:
#+begin_src sh
emacs --init-directory ~/code/nucholab/emacs-config &
#+end_src
Where that argument is the path to where I've cloned this repo. For using the terminal version of this config I end the command with the =-nw= flag instead of the =&=.

* Sources of study and inspiration
** Tutorials, books, and descriptions
   - [ ] Emacs tutorial
   - [ ] System Crafters' [[https://systemcrafters.net/emacs-from-scratch/][Emacs from Scratch]] series
   - [ ] Peter Prevos' [[https://lucidmanager.org/productivity/configure-emacs/][Configure Emacs]] series
   - [ ] [[https://github.com/susam/emfy][Emacs For You]]
   - [ ] Literature from [[https://www.finseth.com/emacs.html][Craig Finseth]]
   - [ ] Mike Zamansky's [[https://cestlaz.github.io/stories/emacs/][Using Emacs]] series [0/81]
   - [ ] Zzambino's configuration [[https://zzamboni.org/post/my-emacs-configuration-with-commentary/][comments]]
   - [ ] [[https://www.masteringemacs.org/][Mastering Emacs]] book and blog
   - [ ] [[https://www2.lib.uchicago.edu/keith/emacs/][The Plain Text Computing Environment]]
   - [ ] Minimal setup [[https://blog.rwhitedwarf.com/post/use_emacs_for_r/][for R]]
   - [ ] ESS [[https://ess.r-project.org/][documentation]]
   - [ ] [[https://tess.oconnor.cx/2009/07/learn-emacs-in-ten-years][Learn Emacs in 10 years]]
   - [ ] Distrotube [[https://www.youtube.com/watch?v=4ZH9pobulDo&list=PL5--8gKSku15uYCnmxWPO17Dq6hVabAB4][video series]] (Derek Taylor)

** Other people's configurations
   - [[https://github.com/Lambda-Emacs][Lambda Emacs]]
   - [[https://github.com/tecosaur/emacs-config][tecosaur]]
   - [[https://github.com/rougier/nano-emacs][NANO Emacs]]
   - [[https://github.com/novoid/dot-emacs][Karl Voit's config]]
   - [[https://github.com/jkitchin/scimax][Scimax]]
   - [[https://github.com/overtone/emacs-live][Emacs Live]]
   - [[https://git.sr.ht/~technomancy/better-defaults][better-defaults]]
   - Derek Taylor's [[https://gitlab.com/dwt1/configuring-emacs][Configuring Emacs]]
   - see other configs [[https://github.com/caisah/emacs.dz][here]].

** Why do this?
#+begin_quote
[...]

Emacs has so much power that nobody will ever master it completely. You can
always be a stronger user with Emacs. With a "simple" editor like pico or
notepad, you will quickly master it completely, which means that it will not
allow you to grow further. Sure, it will take a new user a little longer to be
productive with Emacs than Pico, but by starting with Emacs he will have an
editor that will grow with him for the rest of his life.

[...]

20 MB is 1 cent worth of disc space. For that 1 cent, you get the most powerful
text editor in the world, an IDE that supports more programming languages "out
of the box" than all other IDEs in the world combined, the most feature-rich
News and Mail reader ever, a web browser, a calendar that knows more cultures
than you have heard of, and your own personal psychotherapist. If you think 1
cent is too much for a text editor that has been specially optimized for every
text processing need in your remaining life, you ought to reevaluate your value
system.

[...]

What you call "Windows" is just one of many window systems that has come in and
out of fashion during the lifetime of Emacs. Emacs (in one version or another)
has supported most of them, SunView, NeWS, X10, X11 (Open Look, Athena, Motif),
PM, Win32, Mac. Emacs has provided a sound foundation that has allowed
programmers to be productive with all these, and will also provide a foundation
for whatever window system will be hot tomorrow.

What Emacs doesn't do is to give up that foundation in order to follow the
latest trend. Instead, it incorporates what is good and compensates for the
rest. This -- of course -- will make Emacs feel "old" for the followers of hype,
but the wise will see its intrinsic power and lasting value. ---Per Abrahamsen
#+end_quote
