#+title: Building my Ultimate Emacs Configuration
#+author: nucholab

#+begin_quote
I use emacs, which might be thought of as a thermonuclear word processor [...] emacs outshines all other editing software in approximately the same way that the noonday sun does the stars. It is not just bigger and brighter; it simply makes everything else vanish. ---Neal Stephenson
#+end_quote

This repo is to build my Emacs configuration. The plan is to start with the simplest vanilla config and gradually add features.

** How to use
Currently I'm using the "legacy" config contained in my dotfiles by defailt. Starting with Emacs 29, it is easy to run different configs so I start the one in this repo with:
#+begin_src sh
emacs --init-directory ~/code/nucholab/emacs-config &
#+end_src
Where that argument is the path to where I've cloned this repo. For using the terminal version of this config I end the command with the =-nw= flag instead of the =&=.

* Sources of study and inspiration
** Tutorials, books, and descriptions
   - [ ] System Crafters' [[https://systemcrafters.net/emacs-from-scratch/][Emacs from Scratch]] series
   - [ ] Peter Prevos' [[https://lucidmanager.org/productivity/configure-emacs/][Configure Emacs]] series
   - [ ] Mike Zamansky's [[https://cestlaz.github.io/stories/emacs/][Using Emacs]] series [/81]
   - [ ] Zzambinu's configuration [[https://zzamboni.org/post/my-emacs-configuration-with-commentary/][comments]]
   - [ ] [[https://www.masteringemacs.org/][Mastering Emacs]] book and blog
   
** Other people's configurations
   - [[https://github.com/Lambda-Emacs][Lambda Emacs]]
   - [[https://github.com/tecosaur/emacs-config][tecosaur]]
   - [[https://github.com/rougier/nano-emacs][NANO Emacs]]
   - [[https://github.com/novoid/dot-emacs][Karl Voit's config]]
   - [[https://github.com/jkitchin/scimax][Scimax]]
   - [[https://github.com/overtone/emacs-live][Emacs Live]]
   - [[https://git.sr.ht/~technomancy/better-defaults][better-defaults]]
   - see other configs [[https://github.com/caisah/emacs.dz][here]].
